### ISSUE TITLE
Add Travis CI to the Repository

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/lemaslab.github.io#12]
Use Travis Continuous Integration (https://travis-ci.com/) to check pull requests automatically.

**Comment by XinsongDu** [comment]
@luran1 Please try to use the following code for `.travis.ym;`, it can trigger travis build on my forked repository. Although it can trigger build, the build will fail. You may need to adjust the content and make it succeed.
```
sudo: required
os: linux
language: ruby
rvm:
 - 2.6.1
 - jruby
install:
 - sudo apt-get install ruby-full build-essential zlib1g-dev
before_script:
 - echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
 - echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
 - echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
 - source ~/.bashrc
 - gem install jekyll bundler
 - source 'https://rubygems.org'
 - gem 'nokogiri'
 - gem 'rack', '~> 2.0.1'
 - gem 'rspec'
 - bundle install
script:
 - bundle exec jekyll build
```
Also, this website might be a good reference about how to write `.travis.yml`: https://docs.travis-ci.com/user/job-lifecycle/

**Comment by luran1** [comment]
was able to get the travis to build, run, and complete. current travis file on my branch works but still needs to be tested against broken code.

solution:
gemfile.lock was within the root directory and has all the files to install. removed all others gem installs and source rubygem.org and replaced with  
bundle install --jobs=3 --retry=3 --deployment

this installs all the gems for the website which was the error that you were previously getting.

**Comment by luran1** [comment]
we can review tomorrow to confirm and continue modifying the travis file
