### ISSUE TITLE
Get Familiar with The Pipeline of Making Changes To The Website

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/lemaslab.github.io#13]
Specific Tasks Would Be:

1. Please create branches with your first name (e.g., for me, the branch name is "xinsong"). Each of us should work under our specific branch, and use pull requests if want to make changes to the master branch.
2. Pull the change to your local computer.
3. Switch to your branch on your local computer.
4. Make a random change.
5. Test your change.
6. Push your change if tested successfully.
7. Make a pull request.

**Comment by luran1** [comment]
I have made my branch and tested a minor change to upload

**Comment by hballard22** [comment]
I've made the branch and made a change to my personal page to upload.

**Comment by nishachachad** [comment]
I have made my branch and made a minor change to my personal page to upload.

**Comment by thulium1** [comment]
I have made a new branch and add a minor change.

**Comment by ygillespie** [comment]
I have made a new branch and added a minor change
