### ISSUE TITLE
Add Hyperlink to Resources

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/lemaslab.github.io#23]
Add "PEP 8 Coding Style for Python" to https://lemaslab.github.io/2019/07/09/starting-in-the-lab.html, and link the words to their webpage https://www.python.org/dev/peps/pep-0008/

**Comment by XinsongDu** [comment]
This can be completed by modifying **/lemaslab.github.io/_posts/2019-07-09-starting-in-the-lab.md**

**Comment by luran1** [comment]
I have the link completed within my branch. Is there a way that I can send a pull request for just this file? I would like to not merge the .travis.yml file to the main yet incase it still needs modifications.

**Comment by XinsongDu** [comment]
@luran1 It's OK, you can merge all of it together after you finish the travis CI. I just saw Dr. Lemas' `good first issue`, in which the specific file needed to be changed is included. So I think maybe it is better to add such information to make the task clearer.
