### ISSUE TITLE
Add Alumni Section to People

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/lemaslab.github.io#24]
Specific tasks:
- Add "Alumni" section to "people" (https://lemaslab.github.io/people/)
- Move Lauren Wright to Alumni
- Update the bottom table for Lauren Wright
- Adjust Braeden's photo to normal scale

**Comment by thulium1** [comment]
I have updated the people page. I also added myself to the page.

**Comment by thulium1** [comment]
There are a lot of people that have graduated. Do we know where they have gone so I can also update those information?

**Comment by XinsongDu** [comment]
Great job @thulium1 ! Please make a pull request to the master branch, do not merge, I will review your code. I see two students already graduated, Lauren Wright: https://www.linkedin.com/in/lauren-wright-7710b411b/, and Yasmin Garcia (I cannot find her linkedin). Just change Lauran's information for now and leave Yasmin's as is, we can email Yasmin asking her.
