### ISSUE TITLE
RUMP Tutorial on Webpage

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/lemaslab.github.io#45]
@hballard22 @nishachachad , great job on creating the document regarding how to run RUMP on Windows! I saw your pull request, but I cannot find it on either "Blog" or "Resources" sections. If you can figure out the reason.

**Comment by nishachachad** [comment]
@XinsongDu The documentation is currently located in the folder labeled "_posts". Is there another location where you would prefer it to be?

**Comment by XinsongDu** [comment]
@nishachachad I think you saved the file in the right location, it should under folder "_posts", but it did not appear on the webpage (https://lemaslab.github.io/blog/). Maybe you can follow [this documentation] and see if you can add a new post to the webpage? I guess there might be something wrong of the format (i.e., other posts starts with two dash lines, but your post starts with a table).

**Comment by XinsongDu** [comment]
It probably should be something like this on top of the file.
---
title: RUMP Personal Computer Documentation
description: Steps outlining running RUMP on a personal computer
categories: blog
---

**Comment by nishachachad** [comment]
I edited the document and made that change. Is that alright or do I have to create a completely new document?

**Comment by XinsongDu** [comment]
@nishachachad Yes, that's the right move, and maybe use "bundle exec jekyll build" to test the webpage on your local machine and see if your post appear? Or you can just make a pull request, I can help with the test. Great job!

**Comment by hballard22** [comment]
I can now see the post on the Lemas Lab website under "Blog"

**Comment by XinsongDu** [comment]
Perfect!
